# Telerobot Configuration
# Copy this file to config.yaml and adjust to match your setup.

robot:
  id: duo_robot
  fps: 30

cameras:
  left_wrist:
    index: 1
    width: 640
    height: 480
  right_wrist:
    index: 0
    width: 640
    height: 480
  main:
    index: 2
    width: 640
    height: 480

arms:
  left:
    type: so100
    port: /dev/tty.usbmodem5A460842561
    use_degrees: true
    cameras: [left_wrist, right_wrist, main]   # which cameras are attached to this arm
    regularization: 1.0e-3
    end_effector_step_sizes: { x: 0.5, y: 0.5, z: 0.5 }
    end_effector_bounds:
      min: [-1.0, -1.0, -1.0]
      max: [1.0, 1.0, 1.0]
    max_ee_step_m: 0.20
    gripper_speed_factor: 20.0
arms:
  right:
    type: so100
    port: /dev/tty.usbmodem58FA0963791
    use_degrees: true
    cameras: []
    regularization: 1.0e-3
    end_effector_step_sizes: { x: 0.5, y: 0.5, z: 0.5 }
    end_effector_bounds:
      min: [-1.0, -1.0, -1.0]
      max: [1.0, 1.0, 1.0]
    max_ee_step_m: 0.20
    gripper_speed_factor: 20.0
